BaseURL = "https://chi.show/"

Title = "Chishow Server"
Author = "Eai"

languageCode = "ja"
hasCJKLanguage = true



[params]
    Description = "Minecraft史上最も池沼なサーバー"

[permalinks]
  news = "news/:title"